# presentation_design.yaml - プレゼンテーションデザインタスクモジュールのメタデータ
id: "task_presentation_design"
name: "プレゼンテーションデザインタスク"
description: "効果的でプロフェッショナルなプレゼンテーションを設計・作成するためのタスクモジュール"
version: "1.0.0"
category: "tasks"

# 依存関係
dependencies: []

# 提供される変数
provides:
  - visual_design_principles
  - storytelling_structure
  - data_visualization_techniques
  - accessibility_guidelines

# 必要な変数
requires:
  - presentation_purpose:
      description: "プレゼンテーションの目的と対象者"
      example: "経営陣向けの新製品提案プレゼンテーション"
  - presentation_duration:
      description: "プレゼンテーションの想定時間"
      example: "20分（質疑応答5分含む）"

# オプション変数
optional_variables:
  - brand_guidelines:
      description: "ブランドガイドラインやコーポレートカラー"
      example: "企業カラー: #1E88E5、フォント: Noto Sans JP"
  - presentation_type:
      description: "プレゼンテーションの種類"
      example: "セールスプレゼンテーション"
  - delivery_format:
      description: "発表形式（対面、オンライン、ハイブリッド）"
      example: "オンライン会議での発表"
  - technical_constraints:
      description: "技術的な制約事項"
      example: "PowerPoint 2019で編集可能であること"
  - accessibility_requirements:
      description: "特別なアクセシビリティ要件"
      example: "視覚障害者への配慮が必要"
  - cultural_context:
      description: "文化的配慮事項"
      example: "国際会議での発表、多文化対応が必要"

# デフォルト値
defaults:
  presentation_type: "ビジネスプレゼンテーション"
  delivery_format: "対面発表"
  slide_aspect_ratio: "16:9"
  font_size_minimum: "24pt（本文）"

# メタデータ
metadata:
  author: "AI Instruction Kits Project"
  created: "2025-07-19"
  updated: "2025-07-19"
  tags:
    - "presentation"
    - "visual design"
    - "storytelling"
    - "data visualization"
    - "public speaking"
    - "business communication"
  references:
    - "Presentation Zen by Garr Reynolds"
    - "Resonate by Nancy Duarte"
    - "WCAG 2.1 Guidelines"
    - "Universal Design Principles"