id: role_coach
name: コーチング役割
description: 個人と組織の成長を支援する専門的なコーチング技術。GROW モデル、ソリューション・フォーカスト・コーチング、認知行動コーチングを含む包括的なアプローチ
version: 1.0.0
category: roles
subcategory: development

# コーチング関連の変数
variables:
  - name: "coaching_approach"
    description: "使用するコーチング手法"
    type: "enum"
    values: ["grow_model", "solution_focused", "cognitive_behavioral", "executive", "life_coaching", "performance", "transformational"]
    default: "grow_model"
    
  - name: "session_type"
    description: "セッションの種類"
    type: "enum"
    values: ["initial_assessment", "goal_setting", "skill_development", "performance_review", "challenge_resolution", "career_transition", "leadership_development"]
    default: "goal_setting"
    
  - name: "development_focus"
    description: "開発の焦点領域"
    type: "enum"
    values: ["leadership", "communication", "performance", "career", "skills", "mindset", "relationships", "work_life_balance"]
    default: "performance"
    
  - name: "questioning_style"
    description: "質問のスタイル"
    type: "enum"
    values: ["socratic", "appreciative", "provocative", "reflective", "solution_focused", "strength_based"]
    default: "socratic"
    
  - name: "session_duration"
    description: "セッションの時間（分）"
    type: "integer"
    default: 60
    min: 30
    max: 120
    
  - name: "relationship_stage"
    description: "コーチング関係のステージ"
    type: "enum"
    values: ["rapport_building", "established", "deep_work", "transition", "completion"]
    default: "established"
    
  - name: "communication_style"
    description: "コミュニケーションスタイル"
    type: "enum"
    values: ["supportive", "challenging", "directive", "non_directive", "collaborative", "empowering"]
    default: "collaborative"
    
  - name: "progress_tracking"
    description: "進捗追跡の方法"
    type: "enum"
    values: ["qualitative", "quantitative", "mixed", "self_assessment", "360_feedback", "behavioral_observation"]
    default: "mixed"
    
  - name: "ethical_framework"
    description: "倫理フレームワーク"
    type: "enum"
    values: ["icf_standards", "organizational_guidelines", "professional_boundaries", "confidentiality_focused"]
    default: "icf_standards"
    
  - name: "cultural_sensitivity"
    description: "文化的配慮レベル"
    type: "enum"
    values: ["standard", "enhanced", "specialized", "cross_cultural"]
    default: "enhanced"

# 他のモジュールとの依存関係
dependencies:
  required:
    - skill_facilitation      # ファシリテーションスキル
  optional:
    - skill_design_thinking   # デザイン思考
    - skill_critical_thinking # 批判的思考
    - skill_problem_solving   # 問題解決

# 互換性のあるタスク
compatible_tasks:
  - task_problem_solving     # 問題解決タスク
  - task_strategy_development # 戦略開発タスク
  - task_project_planning    # プロジェクト計画タスク
  - task_presentation_design # プレゼンテーション設計タスク
  - task_business_planning   # ビジネス計画タスク

# タグ
tags:
  - coaching
  - development
  - leadership
  - performance
  - growth_mindset
  - questioning
  - goal_setting
  - behavioral_change
  - professional_development
  - mentoring
  - facilitation
  - empowerment
  - self_awareness
  - accountability
  - transformation

# 出力形式
output_format:
  structure:
    - session_opening
    - current_state_exploration
    - goal_clarification
    - action_planning
    - commitment_accountability
    - session_closure
  level_of_detail: comprehensive

# 使用例
examples:
  - title: GROWモデルを使った新入社員のパフォーマンス向上
    variables:
      coaching_approach: grow_model
      session_type: performance_review
      development_focus: performance
      questioning_style: socratic
      session_duration: 60
      relationship_stage: established
      communication_style: supportive
    description: 新入社員の業務パフォーマンス向上とキャリア目標設定

  - title: ソリューション・フォーカスト・コーチングによるリーダーシップ開発
    variables:
      coaching_approach: solution_focused
      session_type: leadership_development
      development_focus: leadership
      questioning_style: strength_based
      session_duration: 90
      relationship_stage: deep_work
      communication_style: empowering
    description: マネージャーのリーダーシップスキル強化と チーム管理能力向上

  - title: 認知行動コーチングによるキャリア転換支援
    variables:
      coaching_approach: cognitive_behavioral
      session_type: career_transition
      development_focus: career
      questioning_style: reflective
      session_duration: 75
      relationship_stage: rapport_building
      communication_style: collaborative
      cultural_sensitivity: cross_cultural
    description: 国際的な環境でのキャリア転換と適応支援

  - title: エグゼクティブコーチングによる戦略的思考開発
    variables:
      coaching_approach: executive
      session_type: skill_development
      development_focus: mindset
      questioning_style: provocative
      session_duration: 120
      relationship_stage: established
      communication_style: challenging
      progress_tracking: 360_feedback
    description: 経営幹部の戦略的思考力と意思決定能力の向上

# メタデータ
author: "AI Instruction Kits Project"
created: "2025-07-19"
updated: "2025-07-19"
license: "Apache-2.0"
research_sources:
  - "International Coach Federation (ICF) Standards"
  - "GROW Model (Whitmore)"
  - "Solution-Focused Brief Coaching"
  - "Cognitive Behavioral Coaching"
  - "Co-Active Coaching Model"
  - "Transformational Coaching"
  - "Cultural Intelligence in Coaching"
  - "Neuroscience-based Coaching"