# プロダクション品質モジュールのメタデータ
id: "quality_production"
name: "プロダクション品質"
description: "本番環境向けの品質基準を定義"
version: "1.0.0"
category: "quality"
tags:
  - "production"
  - "quality"
  - "reliability"
  - "performance"

variables:
  - name: "max_error_rate"
    description: "最大エラー率"
    type: "string"
    default: "0.1%"
    
  - name: "availability_target"
    description: "可用性目標"
    type: "string"
    default: "99.9%"
    
  - name: "recovery_time"
    description: "障害復旧時間目標"
    type: "string"
    default: "30分以内"
    
  - name: "response_time_target"
    description: "レスポンス時間目標"
    type: "string"
    default: "200ms以内"
    
  - name: "throughput_target"
    description: "スループット目標"
    type: "string"
    default: "1000 req/sec"
    
  - name: "resource_limits"
    description: "リソース使用制限"
    type: "string"
    default: "CPU: 80%, メモリ: 4GB"
    
  - name: "test_coverage_target"
    description: "テストカバレッジ目標"
    type: "string"
    default: "80%以上"
    
  - name: "code_review_criteria"
    description: "コードレビュー基準"
    type: "string"
    default: "2名以上のレビュー必須"

compatible_with:
  - "task_*"
  - "skill_error_handling"
  - "skill_testing"

author: "AI Instruction Kits Project"
created: "2025-01-10"
updated: "2025-01-10"
license: "Apache-2.0"