# task_documentation.yaml - 技術文書作成タスクモジュールのメタデータ
id: "task_documentation"
name: "技術文書作成タスク"
description: "明確で包括的な技術文書を作成するためのタスクモジュール"
version: "1.0.0"
category: "tasks"

# 依存関係
dependencies: []

# 提供される変数
provides:
  - documentation_methodology
  - technical_writing_principles
  - format_standards
  - docs_as_code

# 必要な変数
requires:
  - document_type:
      description: "作成する文書の種類"
      example: "APIリファレンス、ユーザーマニュアル、開発者ガイド"
  - target_audience:
      description: "想定読者"
      example: "初級開発者、システム管理者、エンドユーザー"

# オプション変数
optional_variables:
  - document_purpose:
      description: "文書の具体的な目的"
      example: "REST APIの使用方法を開発者に説明する"
  - audience_analysis:
      description: "詳細な読者分析"
      example: "Python経験3年以上の開発者、RESTful APIの基本知識あり"
  - writing_style:
      description: "執筆スタイルのガイドライン"
      example: "簡潔で直接的、技術用語は最小限に"
  - content_elements:
      description: "含めるべきコンテンツ要素"
      example: "クイックスタート、詳細リファレンス、トラブルシューティング"
  - documentation_format:
      description: "文書フォーマット"
      example: "Markdown、DITA XML、HTML"
  - api_documentation:
      description: "API文書固有の要件"
      example: "true（APIドキュメントの場合）"
  - accessibility_requirements:
      description: "アクセシビリティ要件"
      example: "WCAG 2.1 Level AA準拠"

# デフォルト値
defaults:
  format_preference: "適切なフォーマットを選択（Markdown推奨）"
  version_control: "Gitでバージョン管理"
  update_frequency: "継続的な更新"
  review_process: "技術レビューと読者テスト"

# メタデータ
metadata:
  author: "AI Instruction Kits Project"
  created: "2025-01-16"
  updated: "2025-01-16"
  tags:
    - "technical writing"
    - "documentation"
    - "API docs"
    - "user manuals"
    - "DITA"
    - "markdown"
    - "docs-as-code"
  references:
    - "Technical Writing Best Practices 2024"
    - "API Documentation Standards"
    - "DITA 1.3 Specification"
    - "Docs-as-Code Methodology"