id: task_thesis_writing
name: 論文執筆タスク
description: 2024-2025年の最新学位論文・研究論文執筆タスク。論文構造設計、執筆プロセス管理、デジタルツール活用、品質向上戦略を含む包括的な実践的アプローチ
version: 1.0.0
category: tasks
subcategory: academic_writing

# 論文執筆関連の変数
variables:
  - name: "thesis_type"
    description: "論文タイプ"
    type: "enum"
    values: ["bachelor", "master", "doctoral", "research_article", "monograph", "article_based"]
    default: "doctoral"
    
  - name: "thesis_format"
    description: "論文形式"
    type: "enum"
    values: ["traditional_monograph", "publication_based", "three_paper", "hybrid", "creative_work"]
    default: "traditional_monograph"
    
  - name: "discipline"
    description: "学問分野"
    type: "enum"
    values: ["stem", "social_sciences", "humanities", "interdisciplinary", "professional", "applied"]
    default: "interdisciplinary"
    
  - name: "writing_stage"
    description: "執筆段階"
    type: "enum"
    values: ["planning", "literature_review", "methodology", "data_collection", "analysis", "writing", "revision", "submission"]
    default: "writing"
    
  - name: "timeline"
    description: "執筆期間"
    type: "enum"
    values: ["3_months", "6_months", "1_year", "2_years", "3_years", "flexible"]
    default: "1_year"
    
  - name: "writing_tool"
    description: "主要執筆ツール"
    type: "enum"
    values: ["word", "latex", "google_docs", "scrivener", "markdown", "mixed"]
    default: "latex"
    
  - name: "collaboration_level"
    description: "共同執筆レベル"
    type: "enum"
    values: ["solo", "advisor_only", "committee", "co_authors", "research_group"]
    default: "advisor_only"
    
  - name: "language"
    description: "執筆言語"
    type: "enum"
    values: ["japanese", "english", "bilingual", "multilingual", "translation_needed"]
    default: "english"
    
  - name: "chapter_count"
    description: "章数"
    type: "enum"
    values: ["5_chapters", "6_8_chapters", "9_12_chapters", "flexible", "article_collection"]
    default: "6_8_chapters"
    
  - name: "revision_depth"
    description: "改訂深度"
    type: "enum"
    values: ["minimal", "standard", "extensive", "multiple_rounds", "continuous"]
    default: "extensive"
    
  - name: "quality_target"
    description: "品質目標"
    type: "enum"
    values: ["pass", "good", "excellent", "publication_ready", "award_worthy"]
    default: "excellent"
    
  - name: "support_system"
    description: "支援体制"
    type: "enum"
    values: ["minimal", "standard", "comprehensive", "writing_center", "professional_editing"]
    default: "standard"
    
  - name: "digital_tools"
    description: "デジタルツール活用"
    type: "enum"
    values: ["basic", "intermediate", "advanced", "integrated", "ai_enhanced"]
    default: "advanced"
    
  - name: "workflow_type"
    description: "ワークフロータイプ"
    type: "enum"
    values: ["linear", "iterative", "agile", "spiral", "adaptive"]
    default: "iterative"
    
  - name: "stress_level"
    description: "ストレスレベル"
    type: "enum"
    values: ["low", "manageable", "moderate", "high", "critical"]
    default: "moderate"

# 他のモジュールとの依存関係
dependencies:
  required:
    - expertise_academic_writing  # 学術文章作成専門知識
    - skill_citation_management  # 引用管理スキル
    - skill_literature_review    # 文献レビュースキル
  optional:
    - method_research_methodology # 研究方法論
    - skill_time_management      # 時間管理スキル
    - skill_project_management   # プロジェクト管理スキル
    - skill_data_visualization   # データ可視化スキル
    - task_grant_writing        # 研究費申請タスク

# 互換性のあるタスク
compatible_tasks:
  - task_literature_review      # 文献レビュー
  - task_data_analysis         # データ分析
  - task_conference_presentation # 学会発表
  - task_journal_submission    # ジャーナル投稿
  - task_dissertation_defense  # 論文審査
  - task_research_planning     # 研究計画
  - task_academic_poster       # 学術ポスター作成

# タグ
tags:
  - thesis_writing
  - dissertation
  - academic_writing
  - research_communication
  - scholarly_publishing
  - graduate_studies
  - writing_process
  - time_management
  - quality_assurance
  - digital_scholarship
  - latex
  - version_control
  - peer_review
  - writing_support
  - motivation

# 出力形式
output_format:
  structure:
    - thesis_outline
    - chapter_templates
    - writing_schedule
    - milestone_checklist
    - revision_plan
    - tool_configuration
    - quality_criteria
    - submission_checklist
  level_of_detail: comprehensive

# 使用例
examples:
  - title: 博士論文3年計画
    variables:
      thesis_type: doctoral
      thesis_format: traditional_monograph
      timeline: 3_years
      chapter_count: 9_12_chapters
      writing_tool: latex
      quality_target: publication_ready
      support_system: comprehensive
    description: 伝統的なモノグラフ形式での博士論文執筆の包括的計画

  - title: 論文ベース修士論文
    variables:
      thesis_type: master
      thesis_format: publication_based
      timeline: 1_year
      chapter_count: article_collection
      collaboration_level: co_authors
      language: english
      workflow_type: agile
    description: 3本の論文を基にした修士論文の効率的執筆

  - title: 学際的研究論文
    variables:
      discipline: interdisciplinary
      writing_stage: analysis
      collaboration_level: research_group
      digital_tools: ai_enhanced
      revision_depth: continuous
      stress_level: high
    description: 複数分野にまたがる共同研究論文の執筆管理

  - title: 迅速論文執筆
    variables:
      timeline: 3_months
      writing_tool: google_docs
      workflow_type: agile
      support_system: writing_center
      quality_target: good
      stress_level: critical
    description: 締切が迫った状況での効率的な論文完成戦略

# メタデータ
author: "AI Instruction Kits Project"
created: "2025-01-20"
updated: "2025-01-20"
license: "Apache-2.0"
research_sources:
  - "Graduate Writing Handbooks 2024-2025"
  - "Thesis and Dissertation Guidelines"
  - "Academic Writing Centers Best Practices"
  - "Digital Tools for Academic Writing"
  - "Writing Productivity Research"
  - "LaTeX Documentation"
  - "Git for Academic Writing"
  - "AI Ethics in Academic Writing"
  - "Time Management for Graduate Students"
  - "Peer Support in Academic Writing"